plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.190'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = minecraft_version + "-" + mod_version
group = mod_group_id

repositories {
    mavenCentral()
    maven { url "https://www.cursemaven.com" }
    maven { url "https://api.modrinth.com/maven" }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main

        // Needed when 'minecraftLibrary' was previously used
        dependencies {
            runtime 'com.moandjiezana.toml:toml4j:0.7.2', {
                exclude module: 'gson'
            }
        }
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    /* --- Compatibility --- */
    compileOnly "curse.maven:apothic-enchanting-1063926:5787344" // 1.2.3
    compileOnly "curse.maven:apothic-attributes-898963:5751458" // 2.4.0
    compileOnly "curse.maven:placebo-283644:5751511" // 9.5.3

    /* --- Test --- */
    implementation "curse.maven:enchantment-descriptions-250419:5793919" // 21.1.4
    implementation "curse.maven:bookshelf-228525:5799640" // 21.1.10
    implementation "curse.maven:prickle-1023259:5780848" // 21.1.4

    // FIXME :: 'johnsmith.enchantingoverhauled.mixin.component.type.ItemEnchantmentsMixin' breaks tooltips
    implementation "maven.modrinth:enchanting-overhauled:CIetGnhb" // 2.1.5

    implementation "curse.maven:obscure-tooltips-715660:7271512" // 4.1.0
    implementation "curse.maven:fragmentum-neoforge-1123977:7271478" // 2.0.19

    /* --- Dependencies --- */
    jarJar(implementation 'com.moandjiezana.toml:toml4j:0.7.2', {
        exclude module: 'gson'
    })
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}